def Settings( **kwargs ):
    return {
        'flags': [
            '-x',
            'c',
            '-Wall',
            '-Wextra',
            '-Werror',
            '-I/usr/include',
            '-I/usr/include/pango-1.0',
            '-I/usr/include/glib-2.0',
            '-I/usr/lib/glib-2.0/include',
            '-I/usr/include/fribidi',
            '-I/usr/include/cairo',
            '-I/usr/include/pixman-1',
            '-I/usr/include/freetype2',
            '-I/usr/include/libdrm',
            '-I/usr/include/libpng16',
            '-I/usr/include/harfbuzz',
            '-I/usr/local/include',
            '-I/usr/local/include/pango-1.0',
            '-I/usr/local/include/glib-2.0',
            '-I/usr/local/lib/glib-2.0/include',
            '-I/usr/local/include/fribidi',
            '-I/usr/local/include/cairo',
            '-I/usr/local/include/pixman-1',
            '-I/usr/local/include/freetype2',
            '-I/usr/local/include/libdrm',
            '-I/usr/local/include/libpng16',
            '-I/usr/local/include/harfbuzz',
            '-D_THREAD_SAFE',
            '-pthread' ],
    }
