#ifndef __ATOMS_H__
#define __ATOMS_H__

#include <X11/Xlib.h>
#include <X11/Xatom.h>

enum AtomType {
    /* icccm */
    AtomWMDeleteWindow,
    AtomWMTakeFocus,
    AtomWMProtocols,

    /* ewmh */
    AtomNetSupported,
    AtomNetClientList,
    AtomNetClientListStacking,
    AtomNetNumberOfDesktops,
    AtomNetDesktopGeometry,
    AtomNetDesktopViewport,
    AtomNetCurrentDesktop,
    AtomNetDesktopNames,
    AtomNetActiveWindow,
    AtomNetWorkarea,
    AtomNetSupportingWMCheck,
    AtomNetVirtualRoots,
    AtomNetDesktopLayout,
    AtomNetShowingDesktop,
    AtomNetCloseWindow,
    AtomNetMoveresizeWindow,
    AtomNetWMMoveresize,
    AtomNetRestackWindow,
    AtomNetRequestFrameExtents,
    AtomNetWMName,
    AtomNetWMVisibleName,
    AtomNetWMIconName,
    AtomNetWMVisibleIconName,
    AtomNetWMDesktop,
    AtomNetWMWindowType,
    AtomNetWMState,
    AtomNetWMAllowedActions,
    AtomNetWMStrut,
    AtomNetWMStrutpartial,
    AtomNetWMIconGeometry,
    AtomNetWMIcon,
    AtomNetWMPID,
    AtomNetWMHandledIcons,
    AtomNetWMUserTime,
    AtomNetWMUserTimeWindow,
    AtomNetFrameExtents,
    AtomNetWMPing,
    AtomNetWMSyncRequest,
    AtomNetWMSyncRequestCounter,
    AtomNetWMFullscreenMonitors,
    AtomNetWMFullPlacement,
    AtomNetWMWindowTypeDesktop,
    AtomNetWMWindowTypeDock,
    AtomNetWMWindowTypeToolbar,
    AtomNetWMWindowTypeMenu,
    AtomNetWMWindowTypeUtility,
    AtomNetWMWindowTypeSplash,
    AtomNetWMWindowTypeDialog,
    AtomNetWMWindowTypeDropdownMenu,
    AtomNetWMWindowTypePopupMenu,
    AtomNetWMWindowTypeTooltip,
    AtomNetWMWindowTypeNotification,
    AtomNetWMWindowTypeCombo,
    AtomNetWMWindowTypeDnd,
    AtomNetWMWindowTypeNormal,
    AtomNetWMStateModal,
    AtomNetWMStateSticky,
    AtomNetWMStateMaximizedVert,
    AtomNetWMStateMaximizedHorz,
    AtomNetWMStateShaded,
    AtomNetWMStateSkipTaskbar,
    AtomNetWMStateSkipPager,
    AtomNetWMStateHidden,
    AtomNetWMStateFullscreen,
    AtomNetWMStateAbove,
    AtomNetWMStateBelow,
    AtomNetWMStateDemandsAttention,
    AtomNetWMActionMove,
    AtomNetWMActionResize,
    AtomNetWMActionMinimize,
    AtomNetWMActionShade,
    AtomNetWMActionStick,
    AtomNetWMActionMaximizeHorz,
    AtomNetWMActionMaximizeVert,
    AtomNetWMActionFullscreen,
    AtomNetWMActionChangeDesktop,
    AtomNetWMActionClose,
    AtomNetWMActionAbove,
    AtomNetWMActionBelow,

    AtomCount
};

extern Atom stAtoms[AtomCount];

void InitializeAtoms();

#endif
